version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18002:18002"
    environment:
      HTTP_LISTEN_PORT: 18002
      DB_ENGINE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: jumpserver
      DB_USER: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: jumpserver
      BOOTSTRAP_TOKEN: jumpserver
      BASE_SITE_URL: http://localhost:8080
      AUTH_OIDC: "True"
      OIDC_RP_CLIENT_ID: 813411115863-aj5ip1hjjgumfsb8tm7g12femtia065l.apps.googleusercontent.com
      OIDC_RP_CLIENT_SECRET: ${OIDC_RP_CLIENT_SECRET:-secret}
      OIDC_OP_AUTHORIZATION_ENDPOINT: https://accounts.google.com/o/oauth2/v2/auth
      OIDC_OP_TOKEN_ENDPOINT: https://oauth2.googleapis.com/token
      OIDC_OP_USER_ENDPOINT: https://openidconnect.googleapis.com/v1/userinfo
      OIDC_RP_SIGN_ALGO: RS256
      OIDC_OP_JWKS_ENDPOINT: https://www.googleapis.com/oauth2/v3/certs
      LOGIN_REDIRECT_URL: http://localhost:18002
      LOGOUT_REDIRECT_URL: http://localhost:18002
    volumes:
      - .:/opt/jumpserver
    depends_on:
      - nginx
      - mysql
      - redis
      - phpmyadmin

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./initdb:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jumpserver

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
    - "18004:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
    - mysql

  redis:
    image: 'bitnami/redis:5.0'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_PASSWORD=secret
